language: python
sudo: false

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5

install:
    - pip install tox tox-travis

script:
    - tox --skip-missing-interpreters -e $TOX_ENV
env:
    - TOX_ENV=py26-dj16
    - TOX_ENV=py27-dj16
    - TOX_ENV=py27-dj18
    - TOX_ENV=py27-dj19
    - TOX_ENV=py27-dj110
    - TOX_ENV=py27-dj111
    - TOX_ENV=py33-dj16
    - TOX_ENV=py33-dj18
    - TOX_ENV=py34-dj18
    - TOX_ENV=py34-dj19
    - TOX_ENV=py34-dj110
    - TOX_ENV=py34-dj111
    - TOX_ENV=py35-dj18
    - TOX_ENV=py35-dj19
    - TOX_ENV=py35-dj110
    - TOX_ENV=py35-dj111
